/** Domain layer public surface — types, formatting, aggregation, input rules. */
export type {
  TxType,
  Repeat,
  WeekendShift,
  Transaction,
  RecurrenceDate,
  RecurrenceOccurrence,
  RecurrenceRule,
  Ledger,
  Currency,
  YM,
  ImportProvenance,
} from './types';
export type { CategoryEntity } from './identity';
export { stableId, legacyCategoryId, categoryEntities, legacyCategoryEntities, categoryIdFor, withCategoryId } from './identity';
export {
  PAIRING_VERSION,
  DEFAULT_INVITATION_TTL_MS,
  KEYCHAIN_SERVICE,
  createHousehold,
  createInvitation,
  joinHousehold,
  revokeDevice,
  householdKeyAccount,
  storeHouseholdKey,
  loadHouseholdKey,
  deleteHouseholdKey,
  createAuthenticatedEnvelope,
  openAuthenticatedEnvelope,
  PairingError,
  type DeviceAuthorization,
  type PendingInvitation,
  type HouseholdPairingState,
  type HouseholdCreation,
  type InvitationCreation,
  type JoinResult,
  type RevocationResult,
  type PairingFailure,
  type KeychainSecretStore,
  type AuthenticatedEnvelope,
  type OpenEnvelopeOptions,
} from './pairing';
export {
  RECOVERY_PACK_VERSION,
  exportRecoveryPack,
  openRecoveryPack,
  restoreRecoveryPack,
  RecoveryPackError,
  type RecoverySnapshot,
  type RecoveryStore,
  type DeviceAuthenticator,
  type RecoveryFailure,
} from './recoveryPack';
export {
  HOUSEHOLD_BACKUP_FORMAT,
  HOUSEHOLD_BACKUP_VERSION,
  HOUSEHOLD_BACKUP_MIN_VERSION,
  HOUSEHOLD_BACKUP_EXCLUDED_FIELDS,
  createHouseholdBackup,
  readHouseholdBackup,
  previewHouseholdBackup,
  restoreHouseholdBackup,
  HouseholdBackupError,
  type HouseholdBackup,
  type HouseholdBackupPayload,
  type HouseholdBackupPreview,
  type HouseholdBackupRestore,
  type HouseholdBackupStore,
  type HouseholdBackupFailure,
} from './householdBackup';
export {
  DEFAULT_EXP_CATS,
  DEFAULT_INC_CATS,
  DEFAULT_CURRENCY,
} from './defaults';
export { yen, signed, code, stamp, MINUS } from './format';
export { emojiFor, FALLBACK_EMOJI } from './emoji';
export {
  monthEntries,
  dayEntries,
  dayNet,
  income,
  expense,
  net,
  signedAmount,
  makeEntry,
  updateEntry,
  removeEntry,
  uid,
  type EntryDraft,
} from './entries';
export {
  daysInMonth,
  firstWeekday,
  shiftMonth,
  clampDay,
  WEEKDAYS,
  WEEKDAY_ABBR,
  MONTH_NAMES,
  dayLabel,
  CALENDAR_VIEWS,
  isCalendarView,
  type CalendarView,
} from './calendar';
export {
  categoryBreakdown,
  splitProportions,
  SUMMARY_GRANULARITIES,
  isSummaryGranularity,
  periodEntries,
  periodKey,
  periodLabel,
  periodMonths,
  shiftPeriod,
  type CategorySlice,
  type Split,
  type SummaryGranularity,
} from './summary';
export {
  activeRecurrences,
  saveLedgerItem,
  entriesForMonth,
  deleteLedgerItem,
  entriesThrough,
  type ActiveRecurrence,
} from './recurrence';
export {
  CURRENCIES,
  addCategory,
  removeCategory,
  moveCategory,
  promoteCategory,
} from './categories';
export {
  setBudget,
  clearBudget,
  hasAnyBudget,
  budgetRemaining,
  pruneBudgets,
  isBudgetActive,
  getRemainingBudget,
  getTodayAllowance,
  type TodayAllowance,
  type TodayAllowanceStatus,
  type Budgets,
} from './budgets';
export {
  decodeZaimBytes,
  parseZaimCsv,
  serializeZaimCsv,
  zaimImportAdapter,
  type ZaimExisting,
  type ZaimImportResult,
  type ZaimSkipReason,
  type ZaimSkipTally,
} from './zaim';
export {
  decodeOkaneRecoBytes,
  okaneRecoImportAdapter,
} from './okaneReco';
export {
  decodeMoneyforwardMeBytes,
  moneyforwardMeImportAdapter,
} from './moneyforward';
export {
  validateFinancialRow,
  type FinancialRow,
  type FinancialRowInvalidReason,
  type FinancialRowValidation,
} from './financialRow';
export {
  previewImport,
  previewImportBytes,
  applyImport,
  applyImportPreview,
  sourceFingerprint,
  type ImportAdapter,
  type ImportDetection,
  type NormalizedImportRow,
  type AdapterParseResult,
  type ImportPreview,
  type ImportState,
  type ImportSkipReason,
  type ImportSkipTally,
} from './importPipeline';
export {
  createSyncState,
  addLocalTransaction,
  editLocalTransaction,
  deleteLocalTransaction,
  restoreLocalTransaction,
  rollbackLocalTransaction,
  applySyncOperation,
  applySyncOperations,
  stageSyncOperations,
  createSyncStateTransfer,
  applySyncStateTransfer,
  validateSyncOperation,
  isSyncActorId,
  isSyncHouseholdId,
  isSyncState,
  isHouseholdConfigState,
  isRecurrenceSyncState,
  type ActorId,
  type HouseholdId,
  type VersionVector,
  type AddTransactionOperation,
  type EditTransactionOperation,
  type DeleteTransactionOperation,
  type TransactionAttribution,
  type SyncHistoryEntry,
  type Tombstone,
  type SyncOperation,
  type SyncState,
  type SyncApplyResult,
  type SyncBatchPreview,
  type SyncRollbackMetadata,
  type SyncValidationError,
  type SharedCategory,
  type HouseholdConfigState,
  type AddCategoryOperation,
  type RenameCategoryOperation,
  type DeleteCategoryOperation,
  type SetCategoryBudgetOperation,
  type SetTotalBudgetOperation,
  type SetCurrencyOperation,
  type HouseholdConfigOperation,
  type HouseholdConfigHistoryEntry,
  type ConfigApplyResult,
  type AddRecurrenceRuleOperation,
  type EditRecurrenceRuleOperation,
  type ExceptionRecurrenceOperation,
  type SplitRecurrenceRuleOperation,
  type DeleteRecurrenceRuleOperation,
  type RecurrenceSyncOperation,
  type RecurrenceHistoryEntry,
  type RecurrenceSyncState,
  type RecurrenceSyncApplyResult,
} from './sync';
export {
  householdSyncStatus,
  syncHistoryRows,
  syncFailureMessage,
  type HouseholdSyncStatus,
  type SyncStatusFacts,
  type SyncStatusModel,
  type SyncHistoryChange,
  type SyncHistoryRow,
  type SyncFailureMessage,
} from './syncPresentation';
export {
  NEARBY_PROTOCOL_VERSION,
  NEARBY_SERVICE_TYPE,
  NearbySyncCoordinator,
  createMultipeerConnectivityTransport,
  nearbyDiscoveryInfo,
  type NearbyPeer,
  type NearbyTransport,
  type NearbyTransportHandlers,
  type MultipeerConnectivityModule,
  type NearbyOperationBatch,
  type NearbyOperationAck,
  type NearbySyncCoordinatorOptions,
  type NearbySyncContext,
  type NearbyApplyResult,
  type NearbyQueueSnapshot,
  type NearbyQueueStore,
} from '../platform/nearbySync';
export { createNearbyQueueStore, nearbyQueueStorageKey } from '../platform/nearbyQueueStore';
export {
  createHouseholdConfigState,
  addLocalCategory,
  renameLocalCategory,
  deleteLocalCategory,
  setLocalCategoryBudget,
  setLocalTotalBudget,
  setLocalCurrency,
  applyHouseholdConfigOperation,
  applyHouseholdConfigOperations,
  createRecurrenceSyncState,
  addLocalRecurrenceRule,
  editLocalRecurrenceRule,
  addRecurrenceException,
  splitLocalRecurrenceRule,
  deleteLocalRecurrenceRule,
  applyRecurrenceSyncOperation,
  applyRecurrenceSyncOperations,
  validateRecurrenceSyncOperation,
  stableOccurrenceId,
} from './sync';
export {
  pressKey,
  amountValue,
  AMOUNT_MAX_DIGITS,
  type KeypadKey,
} from './keypad';
export {
  QUICK_ENTRY_COMMAND_VERSION,
  validateQuickEntryCommand,
  quickEntryCommandKey,
  quickEntryTransactionId,
  transactionFromQuickEntryCommand,
  reconcileQuickEntryCommands,
  type QuickEntryCommand,
  type QuickEntryDate,
  type QuickEntryReconciliation,
  type QuickEntryValidationError,
} from './quickEntry';
