int snd_seq_port_subscribe_malloc(void) { return -1; }
int snd_seq_port_subscribe_sizeof(void) { return -1; }
int snd_seq_port_info_malloc(void) { return -1; }
int snd_seq_get_any_port_info(void) { return -1; }
int snd_seq_port_info_free(void) { return -1; }
int snd_seq_port_info_get_client(void) { return -1; }
int snd_seq_port_info_get_port(void) { return -1; }
int snd_seq_port_info_set_client(void) { return -1; }
int snd_seq_port_info_set_port(void) { return -1; }
int snd_seq_query_next_port(void) { return -1; }
int snd_seq_client_info_malloc(void) { return -1; }
int snd_seq_client_info_set_client(void) { return -1; }
int snd_seq_query_next_client(void) { return -1; }
int snd_seq_client_info_get_client(void) { return -1; }
int snd_seq_client_info_free(void) { return -1; }
int snd_seq_port_info_get_type(void) { return -1; }
int snd_seq_port_info_get_capability(void) { return -1; }
int snd_seq_open(void) { return -1; }
int snd_seq_set_client_name(void) { return -1; }
int snd_seq_close(void) { return -1; }
int snd_seq_create_simple_port(void) { return -1; }
int snd_seq_client_id(void) { return -1; }
int snd_seq_port_subscribe_set_sender(void) { return -1; }
int snd_seq_port_subscribe_set_dest(void) { return -1; }
int snd_seq_port_subscribe_set_time_update(void) { return -1; }
int snd_seq_port_subscribe_set_time_real(void) { return -1; }
int snd_seq_subscribe_port(void) { return -1; }
int snd_midi_event_new(void) { return -1; }
int snd_seq_port_subscribe_free(void) { return -1; }
int snd_seq_get_any_client_info(void) { return -1; }
int snd_seq_client_info_get_name(void) { return -1; }
int snd_seq_port_info_get_name(void) { return -1; }
int snd_seq_alloc_named_queue(void) { return -1; }
int snd_seq_queue_tempo_malloc(void) { return -1; }
int snd_seq_queue_tempo_sizeof(void) { return -1; }
int snd_seq_queue_tempo_set_tempo(void) { return -1; }
int snd_seq_queue_tempo_set_ppq(void) { return -1; }
int snd_seq_set_queue_tempo(void) { return -1; }
int snd_seq_drain_output(void) { return -1; }
int snd_seq_queue_tempo_free(void) { return -1; }
int snd_seq_port_info_sizeof(void) { return -1; }
int snd_seq_port_info_set_capability(void) { return -1; }
int snd_seq_port_info_set_type(void) { return -1; }
int snd_seq_port_info_set_midi_channels(void) { return -1; }
int snd_seq_port_info_set_timestamping(void) { return -1; }
int snd_seq_port_info_set_timestamp_real(void) { return -1; }
int snd_seq_port_info_set_timestamp_queue(void) { return -1; }
int snd_seq_port_info_set_name(void) { return -1; }
int snd_seq_create_port(void) { return -1; }
int snd_seq_control_queue(void) { return -1; }
int snd_midi_event_no_status(void) { return -1; }
int snd_seq_poll_descriptors_count(void) { return -1; }
int snd_seq_poll_descriptors(void) { return -1; }
int snd_seq_event_input_pending(void) { return -1; }
int snd_seq_event_input(void) { return -1; }
int snd_midi_event_decode(void) { return -1; }
int snd_midi_event_free(void) { return -1; }
int snd_seq_port_subscribe_get_sender(void) { return -1; }
int snd_seq_port_subscribe_get_dest(void) { return -1; }
int snd_seq_unsubscribe_port(void) { return -1; }
int snd_seq_delete_port(void) { return -1; }
int snd_seq_free_queue(void) { return -1; }
int snd_midi_event_resize_buffer(void) { return -1; }
int snd_midi_event_encode(void) { return -1; }
int snd_seq_event_output_direct(void) { return -1; }
